name: gitpicker
description: Um facilitador para achar usuários e ter um resumo do seu perfil no Github.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  shimmer: ^1.1.0
  transparent_image: ^1.0.0
  font_awesome_flutter: ^8.7.0
  json_serializable: ^3.2.5
  dio: ^3.0.9
  flutter_mobx: ^1.0.1
  mobx: ^1.0.2+2
  flutter_modular: ^0.5.6
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.2
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs